# Generated by Django 4.1.7 on 2024-11-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('alerta', '0004_departamento_industria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='industria',
        ),
        migrations.AddField(
            model_name='alerta',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeo.departamento'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeo.provincia'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeo.distrito'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
        migrations.DeleteModel(
            name='Industria',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
