# Generated by Django 4.1.7 on 2024-11-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0005_remove_distrito_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='alerta',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='industria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alerta.industria'),
        ),
    ]
