# Generated by Django 4.1.7 on 2024-11-18 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('curriculum', '0003_curriculum_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeo.departamento'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeo.distrito'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeo.provincia'),
        ),
    ]
