# Generated by Django 4.1.7 on 2024-11-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_curriculum_departamento_curriculum_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='cargar_curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculum'),
        ),
    ]
